**Generate Random Numbers**

Numpy offers Random module to work with Random numbers

In [2]:
from numpy import random 

x = random.randint(100) # generate a random integer from 0 to 100
print(x)

73


**Generate a random float**

In [3]:
x = random.rand()  # generates a random float from 0 to 1
x

0.7879674842031632

In [4]:
y = random.rand(100) # generates 100 random numbers from 0 to 1.
y

array([0.19535217, 0.7878561 , 0.03605128, 0.72785269, 0.82929107,
       0.90912925, 0.90493148, 0.142178  , 0.8677247 , 0.92392013,
       0.47739939, 0.99470016, 0.38299304, 0.13504566, 0.8709927 ,
       0.72464421, 0.76653845, 0.79100521, 0.6360748 , 0.36905793,
       0.03860171, 0.01200786, 0.78005866, 0.21489314, 0.45922661,
       0.94738268, 0.70124828, 0.33229351, 0.6744349 , 0.20749267,
       0.1198681 , 0.26615139, 0.11979538, 0.77528272, 0.75089334,
       0.17850631, 0.20417378, 0.9709024 , 0.62667206, 0.22638469,
       0.15332447, 0.59557039, 0.75529779, 0.78360155, 0.56292762,
       0.90597404, 0.67646424, 0.89438282, 0.90204904, 0.12817697,
       0.58685892, 0.43215791, 0.06700343, 0.10497599, 0.82014954,
       0.67090034, 0.02063577, 0.26190518, 0.38177761, 0.85971238,
       0.54691709, 0.1612062 , 0.68921267, 0.36843566, 0.93694434,
       0.62872214, 0.92389131, 0.85399607, 0.40346855, 0.90054206,
       0.38770144, 0.18416342, 0.21771821, 0.75031413, 0.48261

In [5]:
x = random.randint(100,size=5) # Generate a 1-D array containing 5 random integers from 0 to 100:
x

array([85, 97, 99,  8, 50])

In [8]:
x = random.randint(100,size=(2,5)) # Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
x

array([[60, 47, 49, 24, 64],
       [59, 66, 20, 70, 51]])

#### **Floats**

The rand() method also allows you to specify the shape of the array.

In [10]:
x = random.rand(5)
x

array([0.95314575, 0.02103504, 0.34441313, 0.45036556, 0.07700806])

In [11]:
x = random.rand(3,5)
x

array([[0.28281813, 0.42803989, 0.11290719, 0.77206978, 0.70466065],
       [0.16989378, 0.41797912, 0.21763522, 0.40307318, 0.67904147],
       [0.54875657, 0.26299577, 0.75079859, 0.97954006, 0.1545937 ]])

## **Generate Random Number From Array**

The **choice()** method allows you to generate a random value based on an array of values.

The **choice()** method takes an array as a parameter and randomly returns one of the values.

In [13]:
x = random.choice([1,2,3,4,5,6,7,8,9])
x

9

The **choice()** method also allows you to return an array of values.

Add a **size** parameter to specify the shape of the array.

In [14]:
x = random.choice([1,2,3,4,5,6,7,8,9],size=(3,5))
x

array([[7, 1, 4, 7, 4],
       [3, 9, 8, 4, 1],
       [1, 5, 4, 6, 9]])

**Random Data Distribution**

**What is Data Distribution?**

Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions.

## **Random Distribution**
A random distribution is a set of random numbers that follow a certain probability density function.

**Probability Density Function: A function that describes a continuous probability. i.e. probability of all values in an array.**

We can generate random numbers based on defined probabilities using the choice() method of the random module.

The choice() method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

Example
Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0

In [15]:
x = random.choice([1,2,3,4],p=[0.6,0.3,0.1,0.0],size =100)
x

array([1, 3, 2, 2, 3, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1,
       3, 1, 1, 3, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 3, 1, 3, 1,
       2, 1, 1, 3, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3,
       1, 2, 2, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 3, 1, 2, 1, 2, 2, 2, 2, 1,
       2, 1, 3, 1, 3, 2, 1, 2, 2, 1, 1, 2])

The sum of all probability numbers should be 1.

In [17]:
x = random.choice([1,2,4,9],p=[0.7,0.1,0.1,0.1],size=(4,5))
x

array([[1, 1, 1, 1, 4],
       [2, 1, 4, 1, 2],
       [9, 1, 1, 1, 1],
       [1, 1, 1, 1, 4]])

**Random Permutations of Elements**

A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: shuffle() and permutation().

**Shuffling Arrays**

Shuffle means changing arrangement of elements in-place. i.e. in the array itself.

In [18]:
import numpy as np
from numpy import random

arr = np.array([1,2,3,4,5,6,7])
random.shuffle(arr)


In [19]:
print(arr)

[6 1 2 7 4 3 5]


The shuffle() method makes changes to the original array.

**Generating Permutation of Arrays**

In [21]:
arr = np.array([1,2,3,4,5,6,7])
print(random.permutation(arr))

[3 6 1 7 4 2 5]


In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7])

The permutation() method returns a re-arranged array (and leaves the original array un-changed).