In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [3]:
print(np.__version__)

1.19.5


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr1 = np.array((1,2,3,4,5,6))
print(arr1)

[1 2 3 4 5 6]


**0-D Arrays**

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [7]:
arr2 = np.array(42)
print(arr2)

42


**1d Arrays**

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [10]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


**2D arrays**

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [9]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


**3D Arrays**

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.



In [13]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.**

In [19]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [20]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Higher Dimensional Arrays**

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [21]:
arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


**NumPy Array Indexing**

Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [22]:
arr = np.array([1,2,3,4,5])
arr[1]

2

In [23]:
arr[1]+arr[2]

5

**Access 2-D Arrays**

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

In [24]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[0,1]

2

**Access 3-D Arrays**

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [25]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
arr[0,1,1]

6

**Negative Indexing**

Use negative indexing to access an array from the end.

In [26]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[1,-2]

9

**NumPy Array Slicing**

**Slicing arrays**


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1



In [27]:
arr = np.array([1,2,3,4,5])
arr[1:5]

array([2, 3, 4, 5])

**Note:** The result includes the start index, but excludes the end index.

In [28]:
arr[4:]

array([5])

In [29]:
arr[:4]

array([1, 2, 3, 4])

In [30]:
arr[-3:-1]

array([3, 4])

In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[1:8:2]

array([2, 4, 6, 8])

In [32]:
arr[::2]

array([1, 3, 5, 7, 9])

**Slicing 2-D Arrays**

In [35]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
arr[1,1:5]

array([ 9, 10, 11, 12])

In [36]:
arr[0:2,3]

array([ 4, 11])

In [37]:
arr[0:2,1:5]

array([[ 2,  3,  4,  5],
       [ 9, 10, 11, 12]])

**NumPy Data Types**


Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.4

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


**Data Types in NumPy**


NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [38]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [39]:
arr = np.array(['apple','banana','mango'])
arr.dtype

dtype('<U6')

**Creating Arrays With a Defined Data Type**

In [43]:
arr = np.array([1,2,3,4,5],dtype = 'S')
print(arr)

[b'1' b'2' b'3' b'4' b'5']


**ValueError:**In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [46]:
arr = np.array(['1','2','3'],dtype = 'i')
arr

array([1, 2, 3], dtype=int32)

In [47]:
arr = np.array(['a','1','2','c'],dtype = 'i')
arr

ValueError: ignored

In [49]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(arr)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
[1 2 3]
int32


In [50]:
arr = np.array([1,0,3])
newarr = arr.astype('bool')
print(arr)
print(newarr)
print(newarr.dtype)

[1 0 3]
[ True False  True]
bool


**NumPy Array Copy vs View**

**The Difference Between Copy and View**

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [53]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[1]=54
print(arr)
print(x)

[ 1 54  3  4  5]
[1 2 3 4 5]


In [54]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[1] = 72
print(arr)
print(x)


[ 1 72  3  4  5]
[ 1 72  3  4  5]


**Check if Array Owns it's Data**

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [55]:
arr = np.array([1,2,3,4,5,6])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5 6]


**The copy returns None.**

**The view returns the original array.** 

# NumPy Array Shape



## Shape of an Array
The shape of an array is the number of elements in each dimension.

## Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [58]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr.shape

(2, 4)

In [60]:
arr = np.array([1,2,3,4,5],ndmin = 5)
arr.shape

(1, 1, 1, 1, 5)

# Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

Reshape From 1-D to 2-D

In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(4,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [65]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr.reshape(2,4).base

array([1, 2, 3, 4, 5, 6, 7, 8])

#### The example above returns the original array, so it is a view.

In [66]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### We can not pass -1 to more than one dimension.

#Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [67]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

# NumPy Array Iterating

## **Iterating Arrays**
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [68]:
arr = np.array([1,2,3])
for i in arr:
  print(i)

1
2
3


In [69]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in arr:
  print(i)

[1 2 3]
[4 5 6]


In [70]:
for i in arr:
  for j in i:
    print(j)

1
2
3
4
5
6


In [71]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [72]:
for i in arr:
  print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [73]:
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## **Iterating Arrays Using nditer()**
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

### Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [74]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i in np.nditer(arr):
  print(i)

1
2
3
4
5
6
7
8


# **Iterating Array With Different Data Types**
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [75]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [77]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


## **Enumerated Iteration Using ndenumerate()**
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [78]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [79]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## NumPy Joining Array

## **Joining NumPy Arrays**
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [82]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [84]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1,arr2),axis = 1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## **Joining Arrays Using Stack Functions**
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [85]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


## **Stacking Along Rows**
NumPy provides a helper function: hstack() to stack along rows.

In [86]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [88]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


**Stacking Along Height (depth)**

NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

## **Splitting NumPy Arrays**
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [90]:
arr = np.array([1, 2, 3, 4, 5, 6])
x = np.array_split(arr,3)
print(x)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [91]:
y = np.array_split(arr,4)
y

[array([1, 2]), array([3, 4]), array([5]), array([6])]

## **Split Into Arrays**
The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [92]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [93]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [94]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [95]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [96]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## **Searching Arrays**
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.



In [97]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [98]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [99]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


## **Search Sorted**
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

In [100]:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [101]:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [103]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)
print(arr)

[1 2 3]
[1 3 5 7]


## **Sorting Arrays**
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [104]:

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [105]:

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [107]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [108]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## **Filtering Arrays**
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [109]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [110]:

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [111]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [112]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [113]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
